name: Homebridge
version: 0.2.2
stage: experimental
slug: homebridge
description: Lightweight HomeKit API implementation with plugin support
url: https://github.com/marcotwin34/hassio-addons
arch:
  - armv7
  - aarch64
  - amd64
ports:
  8581/tcp: 8581
ports_description:
  8581/tcp: Homebridge UI
webui: http://[HOST]:[PORT:8581]
host_network: true
init: false
ingress: true
map:
  - addon_config:rw
  - homeassistant_config:rw
